### ISSUE TITLE
[MIK-61] Avoid using http:// for Google CDN

### ISSUE THREAD

**Issue by CrazyPython** [mikotoIO/mikoto#89]
<sub>From [SyncLinear.com](https://synclinear.com) | [MIK-61](https://linear.app/mikoto/issue/MIK-61/avoid-using-http-for-google-cdn)</sub>

**Comment by TheCactusBlue** [comment]
Apparently this was fixed with the newer CDN service already, although some users may have to reupload their PFPs

**Comment by CrazyPython** [comment]
![image.png](https://uploads.linear.app/d9d13037-c088-4c1e-b684-0938ec2ee646/ab548448-f675-45b5-b9a0-a2916f0b1cd5/4385f640-20f4-4b63-856a-078ef5cb21db)

Still showing as an issue

**Comment by TheCactusBlue** [comment]
Change your pfp

**Comment by TheCactusBlue** [comment]
ok, PFP change is broken again, will need to fix that today
